urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    (r'^grappelli/', include('grappelli.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^$', 'core.views.index'),
    (r'^category/(?P<slug>[^\.]+)/$', 'core.views.view_category'),
    (r'^tour/(?P<slug>[^\.]+)/$', 'core.views.view_tour'),
    (r'^blog/(?P<slug>[^\.]+)/$', 'core.views.view_blog'),
    (r'^page/(?P<slug>[^\.]+)/$', 'core.views.view_page'),
    (r'^partners/$', 'core.views.view_partners'),
    (r'^tours/$', 'core.views.view_tours'),
    (r'^order/$', 'feedback.views.feedback'),
    (r'^thanks/$', 'feedback.views.thanks'),
    (r'^media/(.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    (r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

gallery/models.py
# -*-coding: utf-8-*-
from django.db import models
from blog.models import Post
import os.path
from sorl.thumbnail import ImageField

class GalleryImage(models.Model):
    image = ImageField("Картинка", upload_to='images', help_text="Каритинка, .jpg, .png")
    title = models.CharField("Нащвание картинки", max_length=500, help_text="Заголовок", blank=True)
    parent = models.ManyToManyField('blog.Post', null=True, help_text="Родительская страница", blank=True)

    def get_title(self):
        return self.title if self.title else u'No name'

    class Meta:
        verbose_name_plural = "Картинки"

pages/models.py
# -*-coding: utf-8-*-
from django.db import models
from django.contrib.sites.models import Site
import re
import datetime

class Page(models.Model):
    inmenu = models.BooleanField("В меню", default=False, help_text="Эта страница материалов?")
    service = models.BooleanField("Услуги", default=False, help_text="Эта страница Услуг?")
    slug = models.SlugField("URL", help_text="Если не автоматически, Например: Some_tour, some-tour", unique=True)
    title = models.CharField("Заголовок", max_length=500, help_text="Заголовок")
    seo_descritption = models.TextField("SEO Description", help_text="Описание (Для браузеров)", blank=True)
    seo_keywords = models.TextField("SEO Keywords", help_text="Ключевые слова (Для браузеров)", blank=True)
    body = models.TextField("Контент", help_text="Ипользуется разметка Textile")

    parent = models.ForeignKey('pages.Page', null=True, help_text="Родительская страница", blank=True)

    date = models.DateTimeField("Дата буликации", default=datetime.datetime.now)

    def get_absolute_url(self):
        return 'http://%s/page/%s/' % (Site.objects.get_current().domain, self.slug)

    def get_body(self):
        return re.sub(r'!(?mu)\[(?P<url>.*)\s*\|\s*(?P<name>.*)\s*\|\s*(?P<desc>.*)\]', r"""<figure class="fig-image"><img src="\g<url>" alt="\g<name>" /><figcaption>\g<desc></figcaption></figure>""", self.body)

    def get_description(self):
        body_desc = re.sub(r'!(?mu)\[(?P<url>.*)\s*\|\s*(?P<name>.*)\s*\|\s*(?P<desc>.*)\]', r"""<figure class="fig-image"><img src="\g<url>" alt="\g<name>" /><figcaption>\g<desc></figcaption></figure>""", self.body)
        return body_desc.partition("<!--more-->")[0]

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-date']
        verbose_name_plural = "Страницы сайта"

partners/models.py
# -*-coding: utf-8-*-
from django.db import models
from django.contrib.sites.models import Site
import datetime
from sorl.thumbnail import ImageField

class Partner(models.Model):

    image = ImageField("Картинка", upload_to='images', help_text="Каритинка, .jpg, .png")
    name = models.CharField("Имя", max_length=500, help_text="Заголовок")
    body = models.TextField("Описание", help_text="Ипользуется разметка Textile")

    date = models.DateTimeField("Дата буликации", default=datetime.datetime.now)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['-date']
        verbose_name_plural = "Партнер"

feedback/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms.fields import ChoiceField, MultipleChoiceField
from django.forms.widgets import RadioSelect, CheckboxSelectMultiple


TYPETOUR_CHOICES = (
        ('свадебное путешествие, медовый месяц', 'свадебное путешествие, медовый месяц'),
        ('венчание', 'венчание'),
        ('символическая свадебная церемония', 'символическая свадебная церемония'),
        ('официальное бракосочетание', 'официальное бракосочетание'),
        ('романтический тур', 'романтический тур'),
        ('тур', 'тур'),
        ('другое', 'другое'),
    )
FLYCLASS_CHOICES = (
        ('Первый', 'Первый'),
        ('Бизнес', 'Бизнес'),
        ('Эконом', 'Эконом'),
    )
EATHOTEL_CHOICES = (
        ('OB', 'OB'),
        ('BB', 'BB'),
        ('HB', 'HB'),
        ('FB', 'FB'),
        ('AL', 'AL'),
        ('UAL', 'UAL'),
    )
GUESTPAY_CHOICES = (
        ('Да', 'Да'),
        ('Нет', 'Нет'),
        ('Другое', 'Другое'),
    )
ADVANCE_CHOICES = (
        ('свадебный координатор от нашей компании на месте проведения свадьбы',
         'свадебный координатор от нашей компании на месте проведения свадьбы'),
        ('помощь в организации мальчишника или девичника',
         'помощь в организации мальчишника или девичника'),
        ('помощь в организации расширенной шоу-программы',
         'помощь в организации расширенной шоу-программы'),
        ('Другое',
         'Другое'),
    )

class OrderForm(forms.Form):

    name = forms.CharField(max_length=100)
    phone = forms.CharField(max_length=100)
    email = forms.EmailField("Email")
    date_married = forms.CharField(max_length=100, required=False)
    date_tour = forms.CharField(max_length=100)
    country = forms.CharField(max_length=100)
    budget = forms.CharField(max_length=100)
    hotel_stars = forms.CharField(max_length=100)
    guest = forms.CharField(max_length=100, required=False)
    best_place = forms.CharField(max_length=100, required=False)
    best_country = forms.CharField(max_length=100, required=False)
    full_budget = forms.CharField(max_length=100, required=False)

    type_tour = ChoiceField(widget=RadioSelect, choices=TYPETOUR_CHOICES, required=False)
    fly_class = ChoiceField(widget=RadioSelect, choices=FLYCLASS_CHOICES, required=False)
    eat_hotel = ChoiceField(widget=RadioSelect, choices=EATHOTEL_CHOICES, required=False)
    guest_pay = ChoiceField(widget=RadioSelect, choices=GUESTPAY_CHOICES, required=False)
    advance = ChoiceField(widget=RadioSelect, choices=ADVANCE_CHOICES, required=False)

    message = forms.CharField(widget=forms.Textarea, required=False)
    cc_myself = forms.BooleanField(required=False)

partners/views.py
# Create your views here.

templates/all_tours.html
{% extends "base.html" %}

{% load thumbnail %}
{% load markup %}
{% load site_extras %}
{% load blog_extras %}

{% block lib %}
<script src="/static/js/endless.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/js/endless_on_scroll.js" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block title %}{{ category.title }}{% endblock %}

{% block body_title %}
<h2 class="simple-title"><span class="blue-back-title">Все туры.<span></h2>
{% endblock %}

{% block content %}

    {% include page_template %}

{% endblock %}

{% block rightbar %}
<aside class="right-bar">
    {% show_hot_tours %}
    {% show_banners %}
</aside>
{% endblock %}

templates/archive_page.html
{% load markup %}
{% load endless %}

{% block lib %}
<script src="/static/js/endless.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/js/endless_on_scroll.js" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% paginate post %}

    {% for post in post %}
    <div class="post index-post">
        <h2 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        {% if post.tourpost %}
        <div class="date date-red">{{ post.start_date|date:"j.m.Y" }} - {{ post.end_date|date:"j.m.Y" }}</div>
        {% endif %}
        {% if post.blogpost %}
        <div class="date">{{ post.date|date:"j.m.Y" }}</div>
        {% endif %}
        <article>
            {{ post.get_description|textile }}
        </article>
        <ul class="post-cat-list">
            {% for cat in post.category.all %}
            <li>
                <a href="{{ cat.get_absolute_url }}">{{ cat.title }}</a>{% if not forloop.last %}, {% endif %}
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endfor %}

{% show_more %}

templates/base.html
{% load pages_extras %}
{% load site_extras %}
{% load blog_extras %}
<!DOCTYPE html>
<html lang="ru-RU">
<head>
<title>{% block title %}{% endblock %} - Бутик свадебных путешествий Юлии Фонтаний</title>
<meta name="google-site-verification" content="g6dyUAn9n9r5HbaC5-lh7R-nqrxttbGdrR7wPSQvEhc" />
<meta charset="UTF-8" />
<meta name="author" content="Михаил Якименко" />
{% block descriptions %}
<meta name="keywords" content="" />
<meta name="description" content="" />
{% endblock %}
<link rel="stylesheet" type="text/css" media="all" href="/static/css/style.css" />
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="/static/css/jquery.lightbox-0.5.css" media="screen" />
<script type="text/javascript" src="/static/js/jquery.lightbox-0.5.js"></script>
<script language="JavaScript" type="text/javascript" src="/static/js/slides.jquery.js"></script>
{% block lib %}
{% endblock %}
<!-- Google Fonts -->
<link href='http://fonts.googleapis.com/css?family=Philosopher:400,700,400italic,700italic&subset=latin,cyrillic' rel='stylesheet' type='text/css'>
<!-- Google Fonts -->
{% block js_code %}
<script type="text/javascript">
$(function(){
    $(".menu-pointer").hover(
        function(){
            $(this).find('.pages-menu').show();
        },
        function(){
            $(this).find('.pages-menu').hide();
        }
    );
    $('#gallery a').lightBox();
    $("#slides").slides({
        pagination: false,
        generateNextPrev: false,
        play: 5000,
        effect: 'fade',
    });
})
</script>
{% endblock %}
<!--[if IE]> <script> (function() { var html5 = ("abbr,article,aside,audio,canvas,datalist,details," + "figure,footer,header,hgroup,mark,menu,meter,nav,output," + "progress,section,time,video").split(','); for (var i = 0; i < html5.length; i++) { document.createElement(html5[i]); } })(); </script> <![endif]-->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-13043891-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</head>
<body>
<div class="site-wrapper">
<header class="header">
	<div class="head-logo">
		<a href="/" class="logo"></a>
	</div>
	<div class="head-name-phone">
		<span class="head-site-name">Бутик Свадебных Путешествий</span>
		<span class="head-author-name">Юлии Фонтаний</span>
		<span class="head-site-phone">(044) 361-81-10</span>
	</div>
	<nav class="head-top-nav">
		<ul class="top-nav">
			{% show_menu_service %}
			{% show_menu %}
			<li><a href="/order/">Заказ Путешествия</a></li>
			<li class="online">
				{% show_index_chat %}
			</li>
		</ul>
	</nav>
    <div class="top_show_mask"></div>
    <div class="top_show">
        <div id="slides">
            <div class="slides_container">
                {% show_shows %}
            </div>
        </div>
    </div>
</header>
<aside class="left-bar">
{% show_left_menu %}
</aside>
{% block html_content_tag %}
<section class="content">
{% endblock %}
{% block body_title %}
{% endblock %}
{% block content %}
{% endblock %}
</section>
{% block rightbar %}
{% endblock %}
<div class="cl"></div>
<div class="dash"></div>
<footer class="footer">
	<div class="foot-about">
		<div class="blue-marker">Юлия Фонтаний:</div>
		<span class="foot-about-desc">
			{% show_index_author %}
		</span>
	</div>
	<div class="foot-map">
		<div class="foot-map-block foot-map-adv">
			<div class="blue-marker">Карта сайта:</div>
		</div>
		<div class="foot-map-block">
			<ul class="footer-menu-list">
				<li><a href="/category/novosti/">Новости</a></li>
				<li><a href="/category/romanticheskie-puteshestviya/">Романтические путешествия</a></li>
				<li><a href="/category/turisticheskie-marshruty/">Туристические маршруты</a></li>
				<li><a href="/category/akcii/">Акции</a></li>
				<li><a href="/category/otzyvy/">Отзывы</a></li>
				<li><a href="/category/fotootchet/">Фотоотчет</a></li>
			</ul>
		</div>
		<div class="foot-map-block">
			<ul class="footer-menu-list">
				<li><a href="/page/o-nas/">О нас</a></li>
				<li><a href="/page/kontakty/">Контакты</a></li>
				<li><a href="/order/">Заказ путешествия</a></li>
			</ul>
		</div>
	</div>
</footer>
</div>
</body>
</html>

templates/cat.html
{% extends "base.html" %}

{% load thumbnail %}
{% load markup %}
{% load site_extras %}
{% load blog_extras %}

{% block lib %}
<script src="/static/js/endless.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/js/endless_on_scroll.js" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block title %}{{ category.title }}{% endblock %}

{% block body_title %}
<h2 class="simple-title"><span class="blue-back-title">{{ category.title }}.<span></h2>
{% endblock %}

{% block content %}

	{% include page_template %}

{% endblock %}

{% block rightbar %}
<aside class="right-bar">
    {% show_hot_tours %}
    {% show_banners %}
</aside>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% load thumbnail %}
{% load markup %}
{% load site_extras %}
{% load blog_extras %}

{% block body_title %}
<h2 class="simple-title"><span class="blue-back-title">Новенькое!<span></h2>
{% endblock %}

{% block lib %}
<script src="/static/js/endless.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/js/endless_on_scroll.js" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block content %}

    {% for post in post %}
    <div class="post index-post">
        <h2 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
        {% if post.tourpost %}
        <div class="date date-red">{{ post.start_date|date:"j.m.Y" }} - {{ post.end_date|date:"j.m.Y" }}</div>
        {% endif %}
        {% if post.blogpost %}
        <div class="date">{{ post.date|date:"j.m.Y" }}</div>
        {% endif %}
        <article>
            {{ post.get_description|textile }}
        </article>
        <ul class="post-cat-list">
            {% for cat in post.category.all %}
            <li>
                <a href="{{ cat.get_absolute_url }}">{{ cat.title }}</a>{% if not forloop.last %}, {% endif %}
            </li>
            {% endfor %}
        </ul>
    </div>
    {% endfor %}

{% endblock %}

{% block rightbar %}
<aside class="right-bar">
    {% show_hot_tours %}
    {% show_banners %}
</aside>
{% endblock %}

templates/left-bar.html
{% load site_extras %}

{% show_left_menu %}

templates/order.html
{% extends "base.html" %}

{% load markup %}
{% load site_extras %}

 {% block title %}{{ post.title }}{% endblock %}

{% block html_content_tag %}
<section class="content post-content">
{% endblock %}

{% block body_title %}
<h2 class="simple-title"><span class="blue-back-title">На связи.<span></h2>
{% endblock %}

{% block content %}

<div class="order-box">

  <form class="main-form" method="post">
  {% csrf_token %}

  {{ form.non_field_errors }}

  <div class="form-row form-inp-left form-name">
    <label class="main-l required" for="">Ваше имя:</label>
    {{ form.name }}
    <div class="errors">{{ form.name.errors }}</div>
  </div>

  <div class="form-row form-tuple">
    <div class="form-half form-inp-left">
      <label class="main-l required" for="">Контактный телефон:</label>
      {{ form.phone }}
      <div class="errors">{{ form.phone.errors }}</div>
    </div>
    <div class="form-half form-inp-left">
      <label class="main-l required" for="">email:</label>
      {{ form.email }}
      <div class="errors">{{ form.email.errors }}</div>
    </div>
  </div>

  <div class="form-row form-tuple">
    <div class="form-half form-inp-left">
      <label class="main-l" for="">Планируемая дата свадьбы:</label>
      {{ form.date_married }}
      <div class="errors">{{ form.date_married.errors }}</div>
    </div>
    <div class="form-half form-inp-left">
      <label class="main-l required" for="">Планируемая дата тура:</label>
     {{ form.date_tour }}
     <div class="errors">{{ form.date_tour.errors }}</div>
    </div>
  </div>

  <div class="form-row big-lbl radio-ul">
    <label class="main-l required" for="">Вид путешествия</label>
      {{ form.type_tour }}
      <div class="errors">{{ form.type_tour.errors }}</div>
  </div>

  <div class="form-row form-tuple">
    <div class="form-half form-inp-left">
      <label class="main-l required" for="">Страна:</label>
      {{ form.country }}
      <div class="errors">{{ form.country.errors }}</div>
    </div>
    <div class="form-half form-inp-left">
      <label class="main-l required" for="">Бюджет поездки:</label>
      {{ form.budget }}
      <div class="errors">{{ form.budget.errors }}</div>
    </div>
  </div>

  <div class="form-row big-lble radio-ul">
    <label class="main-l" for="">Класс перелета:</label>
    {{ form.fly_class }}
    <div class="errors">{{ form.fly_class.errors }}</div>
  </div>

  <div class="form-row form-inp-left">
    <label class="main-l required" for="">Категория отеля(1-5 звезд):</label>
    {{ form.hotel_stars }}
    <div class="errors">{{ form.hotel_stars.errors }}</div>
  </div>

  <div class="form-row big-lbl radio-ul">
    <label class="main-l" for="">Питание в отеле:</label>
    {{ form.eat_hotel }}
    <div class="errors">{{ form.eat_hotel.errors }}</div>
  </div>

  <div class="form-row form-inp-left form-guest">
    <label class="main-l" for="">Количество гостей:</label>
    {{ form.guest }}
    <div class="errors">{{ form.guest.errors }}</div>
  </div>

  <div class="form-row big-lbl radio-ul">
    <label class="main-l" for="">Самостоятельно ли гости оплачивают своё путешествие?
(перелёт, проживание, питание, визы, страховки):</label>
   {{ form.guest_pay }}
   <div class="errors">{{ form.guest_pay.errors }}</div>
  </div>

  <div class="form-row form-inp-left">
      <label class="main-l" for="">Лучшее место, по Вашему мнению, для проведения церемонии?</label>
      {{ form.best_place }}
      <div class="errors">{{ form.best_place.errors }}</div>
  </div>

  <div class="form-row form-inp-left">
      <label class="main-l" for="">В какой стране Вы хотели бы провести Свадьбу (или укажите направление)?</label>
      {{ form.best_country }}
      <div class="errors">{{ form.best_country.errors }}</div>
  </div>

  <div class="form-row form-inp-left">
      <label class="main-l" for="">Бюджет свадьбы (включая перелёт, проживание, питание, церемонию, доп. услуги, экскурсии)?</label>
      {{ form.full_budget }}
      <div class="errors">{{ form.full_budget.errors }}</div>
  </div>

  <div class="form-row big-lbl radio-ul">
    <label class="main-l" for="">Интересуют ли Вас дополнительные услуги, которые предлагает наша компания за границей?</label>
    {{ form.advance }}
    <div class="errors">{{ form.advance.errors }}</div>
  </div>

  <div class="form-row feed-textarea">
    <label class="main-l" for="">Ваши пожелания:</label>
    {{ form.message }}
    <div class="errors">{{ form.message.errors }}</div>
  </div>

  <div class="form-row feed-textarea">
    <label for="id_cc_myself">Отправить мне копию?</label>
    {{ form.cc_myself }}
    <div class="errors">{{ form.cc_myself.errors }}</div>
  </div>

  <input type="submit" />

	</form>

</div>

{% endblock %}

templates/page.html
{% extends "base.html" %}

{% load thumbnail %}
{% load markup %}
{% load site_extras %}

{% block title %}{{ post.title }}{% endblock %}

{% block html_content_tag %}
<section class="content post-content">
{% endblock %}

{% block lib %}
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="/static/css/jquery.lightbox-0.5.css" media="screen" />
<link rel="stylesheet" type="text/css" href="/voyage_search.css">
{% endblock %}

{% block content %}
	<div class="post">
		<header class="h-dashed">
			<h2 class="post-title post-title-in">{{ post.title }}</h2>
			{% if post.start_date %}
			<div class="date date-red">{{ post.start_date|date:"j.m.Y" }} - {{ post.end_date|date:"j.m.Y" }}</div>
			{% endif %}
			{% if post.parent %}
			<ul class="page-child-menu">
				<li>
					Назад к разделу <a href="{{ post.parent.get_absolute_url }}">{{ post.parent.title }}</a>
				</li>
			</ul>
			{% endif %}
			{% if post.page_set.all %}
			<ul class="page-child-menu">
				<li>Страницы раздела: </li>
				{% for item in post.page_set.all %}
				<li>
					<a href="{{ item.get_absolute_url }}">{{ item.title }}</a>{% if not forloop.last %}, {% endif %}
				</li>
				{% endfor %}
			</ul>
			{% endif %}
		</header>
		<article>
			{{ post.get_body|textile }}
		</article>
	</div>
{% endblock %}

templates/partners.html
{% extends "base.html" %}

{% load thumbnail %}
{% load markup %}
{% load site_extras %}

{% block title %}{{ post.title }}{% endblock %}

{% block html_content_tag %}
<section class="content post-content">
{% endblock %}

{% block body_title %}
<h2 class="simple-title"><span class="blue-back-title">Партнеры.<span></h2>
{% endblock %}

{% block content %}

    {% for item in partners %}
    <div class="partner-item">
        <div class="partner-item-img">
            {% thumbnail item.image "160" as image %}
            <img src="{{image.url}}" />
            {% endthumbnail %}
        </div>

        <div class="partner-item-desc">
            <h3>{{ item.name }}</h3>
            {{ item.body|textile }}
        </div>
    </div>
    {% endfor %}

{% endblock %}

templates/post.html
{% extends "base.html" %}

{% load thumbnail %}
{% load markup %}
{% load site_extras %}

{% block title %}{{ post.title }}{% endblock %}

{% block js_code %}
{% endblock %}

{% block html_content_tag %}
<section class="content post-content">
{% endblock %}

{% block content %}
	<div class="post">
		<header class="h-dashed">
			<h2 class="post-title post-title-in"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
			<span class="date">{{ post.date|date:"j.m.Y" }}</span>
			{% if post.start_date %}
			<div class="date date-red">{{ post.start_date|date:"j.m.Y" }} - {{ post.end_date|date:"j.m.Y" }}</div>
			{% endif %}
			<ul class="post-cat-list">
				{% for cat in post.category.all %}
				<li>
					<a href="{{ cat.get_absolute_url }}">{{ cat.title }}</a>{% if not forloop.last %}, {% endif %}
				</li>
				{% endfor %}
			</ul>
		</header>
		<article>
			{{ post.get_body|textile }}
		</article>
	</div>

	{% if post.galleryimage_set.all %}
	<div id="gallery">
		<h2>Галерея</h2>
		<ul>
		{% for photo in post.galleryimage_set.all %}
		{% thumbnail photo.image "x500" as big %}
    		{% thumbnail photo.image "132x80" crop="center" as small %}
        		<li><a href="{{ big.url }}"><img src="{{ small.url }}"></a></li>
    		{% endthumbnail %}
		{% endthumbnail %}
		{% endfor %}
		</ul>
	</div>
	{% endif %}

{% endblock %}

templates/right-bar.html
right

templates/thanks.html
{% extends "base.html" %}

{% load thumbnail %}
{% load markup %}
{% load site_extras %}

{% block title %}{{ post.title }}{% endblock %}

{% block html_content_tag %}
<section class="content post-content">
{% endblock %}

{% block lib %}
<script language="JavaScript" type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="/static/css/jquery.lightbox-0.5.css" media="screen" />
<link rel="stylesheet" type="text/css" href="/voyage_search.css">
{% endblock %}

{% block content %}
	<div class="post index-post">
		<header class="h-dashed">
			<h2 class="post-title post-title-in">Спасибо!</h2>
		</header>
		<article>
			<p>
				{{ thanks }}
			</p>
		</article>
	</div>
{% endblock %}